# Copyright 2026 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# B-lite host (spine) executable. See blite_host.cc.
import("//testing/test.gni")

executable("blite_host") {
  testonly = true
  sources = [ "blite_host.cc" ]
  deps = [
    "//base",
    "//ui/accessibility:accessibility_internal",
  ]
}
